//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucMay
    {
        public int ID { get; set; }
        public string MaHieuMay { get; set; }
        public string TenMayMocThietBi { get; set; }
        public string NoiSuDung { get; set; }
        public string QuanLy { get; set; }
        public string TinhTrang { get; set; }
        public string MaCu { get; set; }
        public string NamMua { get; set; }
        public string GhiChu { get; set; }
    }
}
