//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_VatTu
    {
        public long DeliveryID { get; set; }
        public string Ma_vl { get; set; }
        public string Ten_vat_lieu { get; set; }
        public Nullable<long> id { get; set; }
        public string DienGiai { get; set; }
        public Nullable<double> DinhMuc { get; set; }
        public string DonVi { get; set; }
        public string KhoanMuc { get; set; }
        public Nullable<double> DinhMucDonHang { get; set; }
    }
}
