//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class SANXUATDbContext : DbContext
    {
        public SANXUATDbContext()
            : base("name=SANXUATDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDM_VATTU> tblDM_VATTU { get; set; }
        public virtual DbSet<tblvattu_dauvao> tblvattu_dauvao { get; set; }
        public virtual DbSet<Delivery_VatTu> Delivery_VatTu { get; set; }
        public virtual DbSet<tblDHCT> tblDHCTs { get; set; }
        public virtual DbSet<tblDSNHANVIEN> tblDSNHANVIENs { get; set; }
        public virtual DbSet<Delivery_DatHang> Delivery_DatHang { get; set; }
        public virtual DbSet<Delivery_NhanVien> Delivery_NhanVien { get; set; }
        public virtual DbSet<tblDM_VATLIEUPHU> tblDM_VATLIEUPHU { get; set; }
        public virtual DbSet<tblNHAP_VATLIEUPHU> tblNHAP_VATLIEUPHU { get; set; }
        public virtual DbSet<DeliveryMaterial> DeliveryMaterials { get; set; }
        public virtual DbSet<tblDM_KHUON> tblDM_KHUON { get; set; }
        public virtual DbSet<tblKhungThoiGianLamViec> tblKhungThoiGianLamViecs { get; set; }
        public virtual DbSet<tblResourcesDelivery> tblResourcesDeliveries { get; set; }
        public virtual DbSet<tblDS_GIACONG> tblDS_GIACONG { get; set; }
        public virtual DbSet<DanhMucMay> DanhMucMays { get; set; }
        public virtual DbSet<tblResource> tblResources { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblFunction> tblFunctions { get; set; }
        public virtual DbSet<tblResourcesUser> tblResourcesUsers { get; set; }
        public virtual DbSet<tblUserFunction> tblUserFunctions { get; set; }
        public virtual DbSet<KhachHangPhanLoai> KhachHangPhanLoais { get; set; }
    }
}
