//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDSNHANVIEN
    {
        public string Sothe { get; set; }
        public string HoTen { get; set; }
        public string MaBP { get; set; }
        public string NguoiLap { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string BoPhan { get; set; }
        public int ID { get; set; }
    }
}
