//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDM_VATLIEUPHU
    {
        public long id { get; set; }
        public string Mavlphu { get; set; }
        public string Tenvlphu { get; set; }
        public Nullable<double> Soluong { get; set; }
        public string Donvi { get; set; }
        public string Nguoilap { get; set; }
        public Nullable<System.DateTime> Ngaylap { get; set; }
        public Nullable<double> TongNhap { get; set; }
        public Nullable<double> TongXuat { get; set; }
        public Nullable<double> Toncuoi { get; set; }
        public string ViTri { get; set; }
        public Nullable<double> DinhMucTon { get; set; }
    }
}
