//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDHCT
    {
        public long Iden { get; set; }
        public string Codedetail { get; set; }
        public string Tenkhachhang { get; set; }
        public string Masp_KH { get; set; }
        public string Tenquicach { get; set; }
        public string madh { get; set; }
        public string Khachhang { get; set; }
        public string MaPo { get; set; }
        public string MaSP { get; set; }
        public string dvt { get; set; }
        public string Mau_banve { get; set; }
        public Nullable<double> Tonkho { get; set; }
        public Nullable<double> Soluong { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<double> thanhtien { get; set; }
        public Nullable<System.DateTime> ngaygiao { get; set; }
        public string ngoaiquang { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<double> usd { get; set; }
        public Nullable<double> tygia { get; set; }
        public string ghichu { get; set; }
        public string nguoithaydoi { get; set; }
        public Nullable<System.DateTime> thoigianthaydoi { get; set; }
        public string pheduyet { get; set; }
        public string Nguoiduyet { get; set; }
        public Nullable<System.DateTime> Thoigianduyet { get; set; }
        public string Trangthai { get; set; }
        public string MaKH { get; set; }
        public Nullable<byte> Muc { get; set; }
        public string LoaiDH { get; set; }
        public string PhanloaiKH { get; set; }
        public string Diengiai { get; set; }
        public string Diachi_giaohang { get; set; }
        public Nullable<System.DateTime> Thoigian_Thuc { get; set; }
        public string GhichuXuatKho { get; set; }
        public Nullable<double> DonGiaKhoan { get; set; }
        public Nullable<double> TongTienKhoan { get; set; }
        public Nullable<System.DateTime> NgayLapGiaKhoan { get; set; }
        public string NguoiGhiGiaKhoan { get; set; }
    }
}
