//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDS_GIACONG
    {
        public int Id { get; set; }
        public string MaDVGC { get; set; }
        public string TenDVGC { get; set; }
        public string DiaChi { get; set; }
        public Nullable<decimal> Sodienthoai { get; set; }
        public string fax { get; set; }
        public string Nguoilienhe { get; set; }
        public string usercreate { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
    }
}
