//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDM_KHUON
    {
        public string MaKhuon { get; set; }
        public long KhuonID { get; set; }
        public string TenKhuon { get; set; }
        public string DacDiemKhuon { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string UserCreate { get; set; }
    }
}
