//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDM_VATTU
    {
        public int id { get; set; }
        public string Ma_vl { get; set; }
        public string Ma_loai { get; set; }
        public string Ten_loai { get; set; }
        public string Kich_thuoc_vl { get; set; }
        public string Ten_vat_lieu { get; set; }
        public string Donvi { get; set; }
        public string Donvi_quidoi { get; set; }
        public string MaNCC { get; set; }
        public string Nguoilap { get; set; }
        public Nullable<System.DateTime> Ngaylap { get; set; }
        public string Mahieu { get; set; }
        public Nullable<double> Soluong_ton { get; set; }
        public Nullable<double> TongNhap { get; set; }
        public Nullable<double> TongXuat { get; set; }
        public Nullable<double> TonCuoi { get; set; }
        public Nullable<System.DateTime> MaxNgayNhap { get; set; }
        public Nullable<System.DateTime> MaxNgayXuat { get; set; }
        public string ViTri { get; set; }
        public Nullable<double> DinhMucTon { get; set; }
        public string TenKho { get; set; }
    }
}
