//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhungThoiGianLamViec
    {
        public string Ma { get; set; }
        public int ID { get; set; }
        public string TenGoi { get; set; }
        public Nullable<System.TimeSpan> Tu { get; set; }
        public Nullable<System.TimeSpan> Den { get; set; }
        public string NguoiGhi { get; set; }
        public Nullable<System.DateTime> NgayGhi { get; set; }
        public Nullable<double> HeSo { get; set; }
    }
}
