//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNHAP_VATLIEUPHU
    {
        public long id { get; set; }
        public string Manhap { get; set; }
        public Nullable<System.DateTime> Ngaynhap { get; set; }
        public string Mavlphu { get; set; }
        public string Donvi { get; set; }
        public Nullable<double> Soluong { get; set; }
        public Nullable<double> Dongia { get; set; }
        public Nullable<double> Thanhtien { get; set; }
        public string Nguoilap { get; set; }
        public string Nguoigiao { get; set; }
        public string Diengiai { get; set; }
        public string Nguoinhan { get; set; }
        public string Noinhan { get; set; }
        public Nullable<System.DateTime> Ngayghi { get; set; }
        public Nullable<double> Nhaptam { get; set; }
        public Nullable<double> XuatTT { get; set; }
        public string LoaiNV { get; set; }
        public string BpSuDung { get; set; }
        public string Tenvlphu { get; set; }
        public string DoiTuongCungCap { get; set; }
    }
}
