//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResource
    {
        public string Ma_Nguonluc { get; set; }
        public long ResourceID { get; set; }
        public string Ten_Nguonluc { get; set; }
        public string ToThucHien { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Nguoi { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public Nullable<bool> AllowCheck { get; set; }
    }
}
