//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserFunction
    {
        public string User { get; set; }
        public string Menu { get; set; }
        public Nullable<System.DateTime> SetTime { get; set; }
        public Nullable<bool> AllowAddNew { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
        public Nullable<bool> AllowDelete { get; set; }
        public Nullable<bool> Disable { get; set; }
    }
}
