//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlysanxuat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblvattu_dauvao
    {
        public long CodeVatllieu { get; set; }
        public string Purchase_order { get; set; }
        public string MaDN_VATTU { get; set; }
        public Nullable<long> Iden { get; set; }
        public string madh { get; set; }
        public string Codedetail { get; set; }
        public string Masp { get; set; }
        public string Tenquicachsp { get; set; }
        public Nullable<int> Soluongsanpham { get; set; }
        public string Ma_CT { get; set; }
        public string Ten_CT { get; set; }
        public Nullable<int> QC_CT { get; set; }
        public Nullable<int> Soluong_CT { get; set; }
        public string Donvi_sanpham { get; set; }
        public string Ten_vattu { get; set; }
        public Nullable<int> SL_vattucan { get; set; }
        public Nullable<double> KL_vattucan { get; set; }
        public Nullable<int> SL_vattutonkho { get; set; }
        public Nullable<double> KL_vattutonkho { get; set; }
        public Nullable<double> SL_vattumua { get; set; }
        public Nullable<double> KL_vattumua { get; set; }
        public string Donvi_vattu { get; set; }
        public string NCC { get; set; }
        public string NguoiGD { get; set; }
        public Nullable<double> Dongia { get; set; }
        public string Donviquydoi { get; set; }
        public Nullable<System.DateTime> Ngaydat_vattu { get; set; }
        public Nullable<System.DateTime> NgayDK_ve { get; set; }
        public Nullable<System.DateTime> Ngayve_TT { get; set; }
        public Nullable<double> SL_vattuve { get; set; }
        public Nullable<double> KL_vattuve { get; set; }
        public Nullable<double> SL_tinhgia { get; set; }
        public string Dvt_gia { get; set; }
        public string Ghichu_dathangmua { get; set; }
        public string Ghichu_denghimua { get; set; }
        public string DK_TCmua { get; set; }
        public string VAT { get; set; }
        public string quyetdinh { get; set; }
        public string nhanviendathang { get; set; }
        public string nguoikiemkho { get; set; }
        public Nullable<System.DateTime> ngaykiemkho { get; set; }
        public string nguoinhap { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string fax { get; set; }
        public string NVKD { get; set; }
        public string CodePO { get; set; }
        public Nullable<System.DateTime> NgayDinhViDatVatTu { get; set; }
        public string Ngoaiquan { get; set; }
        public string Ghichu_CT { get; set; }
        public string Ghichu_DH { get; set; }
        public Nullable<System.DateTime> Ngaylap_DM { get; set; }
        public string Nguoilap_DM { get; set; }
        public string Duyetsanxuat { get; set; }
        public string Nguoiduyet { get; set; }
        public Nullable<System.DateTime> Ngayduyet { get; set; }
        public string Kiemkho { get; set; }
        public string Mavattu { get; set; }
        public string MaNCC { get; set; }
        public Nullable<System.DateTime> Ngayxacnhan { get; set; }
        public Nullable<double> DinhMucDonVi { get; set; }
        public string KhoanMuc { get; set; }
        public Nullable<long> SanPhamID { get; set; }
        public Nullable<long> VatTuID { get; set; }
        public Nullable<long> ChiTietID { get; set; }
        public string DienGiai_CachTinh { get; set; }
    }
}
